subject: 'cat:cs.*'

keywords:
    medical imag: 5
    segmentation: 2
    MRI: 3
    quality control: 5
    alzheimer: 5
    parkinson: 5
    multiple sclerosis: 5
    prognosis: 3
    contrastive: 3
    decline: 5
    self-supervised: 2
    semi-supervised: 2

score_threshold: 0
