subject: 'cat:cs.*'

keywords:
    medical imaging: 5
    segmentation: 3
    MRI: 2
    alzheimer: 5
    parkinson: 5
    multiple sclerosis: 5
    prognosis: 3
    cognitive: 3
    decline: 5

score_threshold: 0
